### ISSUE TITLE
Release 0.3.0

### ISSUE THREAD

**Issue by sbauer322** [LightTable/fetch#18]
@kenny-evitt can you please make a release for LightTable/fetch?

I realize this project is probably not active beyond LightTable and that noir is deprecated, but @brabadu's earlier work seems to resolve the warnings during `lein cljsbuild once app` after updating LightTable's clojurescript version for https://github.com/LightTable/LightTable/issues/1973 . Unfortunately, since there is no release containing these changes I was forced to temporarily roll my own release.

**Comment by sbauer322** [comment]
Might also be a good moment to update the clojure version to something like 1.7.0 or 1.8.0 as that is where LightTable is heading.

**Comment by kenny-evitt** [comment]
@sbauer322 I get notifications for all of the LightTable org repos.

I can make a new release. Or maybe not? Light Table is pulling the release package from Clojars and I might need to get in touch with Chris to be able to push a new release. This repo doesn't have any releases or tags so the Clojars releases are probably being created manually. I'm also unsure where the versions 0.2.1 and 0.2.2 are – they're listed on Clojars but the version in this repo is 0.2.0, and there are no branches in the repo other than *master*. @ibdknox Any help you can provide about this?

We might need, or want, to replace this with something else if it's too much trouble getting this sorted out.

I think we should defer bumping the Clojure version, unless you've tested it and you're confident that it doesn't break anything.

**Comment by sbauer322** [comment]
@kenny-evitt the good news is that it looks like there was no real change since 0.2.0. Unless Clojar is lying, both 0.2.1 and 0.2.2 were minor changes to `contributing.md`.

As for the actual creation of the release, I believe it is just one command `lein deploy clojars`.

We'll definitely want to hear from @ibdknox, or maybe @cldwalker if he knows, regarding making a fetch release since LightTable and its projects should be community managed as this point.

I wouldn't be opposed to replacing fetch with something else, especially since fetch has no dedicated maintainer (and noir is essentially deprecated), but I feel updating LT to the latest Clojurescript takes the higher priority for now. We should hold off on updating fetch's clojure dep too, as a result.

**Comment by ibdknox** [comment]
Happy to add whoever wants to be on the fetch repo on Clojars - @kenny-evitt I couldn't find your name on there. 

Looks like I had some changes that I hadn't pushed. They are now. Pretty sure Clojars is lying about the commits, but I tagged what was 0.2.2. In all honesty, you're probably better off just merging the tiny bit of fetch (which is already tiny) into LT itself.

**Comment by sbauer322** [comment]
Thanks for the info @ibdknox! I would recommend @kenny-evitt for the fetch repo on Clojars... If he is unavailable then perhaps @rundis or myself.

**Comment by ibdknox** [comment]
added @rundis and @sbauer322 on there :) Happy to add Kenny too, just need to know the name.

**Comment by sbauer322** [comment]
So fast! Thanks again!

**Comment by kenny-evitt** [comment]
@ibdknox I just registered on Clojars as "kenny-evitt". Thanks for your help with this!

**Comment by ibdknox** [comment]
Added. :)

**Comment by sbauer322** [comment]
[Version 0.3.0](https://clojars.org/fetch/versions/0.3.0) has been released.
